# Generated by Django 6.1.1 on 2026-09-24 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'unique_together': {('name', 'website')},
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=225)),
                ('source_url', models.URLField(unique=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='scraper.company')),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
    ]
