# Generated by Django 6.1.1 on 2026-10-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contract_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='published_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
